module.exports = {
  DocsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Docs',
    },
    {
      type: 'category',
      label: 'SAML Jackson',
      collapsible: true,
      collapsed: false,
      link: { type: 'doc', id: 'jackson/overview' },
      items: [
        {
          type: 'category',
          label: 'Deploy',
          link: { type: 'doc', id: 'jackson/deploy/index' },
          items: [
            'jackson/deploy/service',
            'jackson/deploy/npm-library',
            'jackson/deploy/env-variables',
            'jackson/deploy/pre-loaded-configuration',
          ],
        },
        'jackson/configure-saml-idp',
        'jackson/saml-flow',
        'jackson/examples',
        'jackson/admin-ui',
        'jackson/observability',
        'jackson/sbom',
        'jackson/container-signing',
        'jackson/security',
        'jackson/upgrade',
        'jackson/local-development',
      ],
    },
    {
        type: 'category',
        label: 'Retraced',
        collapsible: true,
        collapsed: false,
        link: { type: 'doc', id: 'retraced/overview/introduction-to-retraced' },
        items: [
          {
            type: 'category',
            label: 'Deploy',
            link: { type: 'doc', id: 'retraced/deploy/index' },
            items: [
                'retraced/deploy/env-variables',
                'retraced/deploy/docker-compose',
                'retraced/deploy/local',
              ],
          },
          {
            type: 'category',
            label: 'How to audit log',
            items: [
                'retraced/how-to-audit-log/audit-logging-basics',
                'retraced/how-to-audit-log/actions',
                'retraced/how-to-audit-log/actors',
                'retraced/how-to-audit-log/exportable',
                'retraced/how-to-audit-log/immutable',
                'retraced/how-to-audit-log/searchable',
                'retraced/how-to-audit-log/segments',
                'retraced/how-to-audit-log/targets',
                'retraced/how-to-audit-log/time-synced',
              ],
          },
          {
            type: 'category',
            label: 'Getting Started',
            items: [
                'retraced/getting-started/retraced-basics',
                'retraced/getting-started/embedded-viewer',
                'retraced/getting-started/first-audit-event',
                'retraced/getting-started/renaming-properties',
                'retraced/getting-started/searching-for-events',
                'retraced/getting-started/time-synchronization',
              ],
          },
          {
            type: 'category',
            label: 'Advanced Retraced',
            items: [
                'retraced/advanced-retraced/advanced-concepts',
                'retraced/advanced-retraced/display-templates',
                'retraced/advanced-retraced/template-comparators',
                'retraced/advanced-retraced/ssh-streaming',
                'retraced/advanced-retraced/tracking-application-versions',
                'retraced/advanced-retraced/automated-audit-events',
              ],
          },
          {
            type: 'category',
            label: 'Exposing Events',
            items: [
                'retraced/exposing-retraced-data/overview',
                'retraced/exposing-retraced-data/viewer',
                'retraced/exposing-retraced-data/enterprise-api',
              ],
          },
          {
            type: 'category',
            label: 'Architecture',
            items: [
                'retraced/architecture/retraced-overview',
                'retraced/architecture/immutability-guarantee',
                'retraced/architecture/hashing-formula',
              ],
          },
          {
            type: 'category',
            label: 'SDKs',
            items: [
                'retraced/sdks/available-sdks',
                'retraced/sdks/golang/getting-started',
                'retraced/sdks/nodejs/getting-started',
              ],
          },
          {
            type: 'category',
            label: 'APIs',
            items: [
                'retraced/apis/overview',
                'retraced/apis/publisher-api',
                'retraced/apis/enterprise-api',
                'retraced/apis/admin-api',
                'retraced/apis/graphql',
              ],
          },
          {
            type: 'category',
            label: 'Troubleshooting',
            items: [
                'retraced/troubleshooting/troubleshooting-retraced',
                'retraced/troubleshooting/daily-email',
                'retraced/troubleshooting/public-ips',
                'retraced/troubleshooting/release-notes',
              ],
          },
        ],
      },
  ],
};
